name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    name: CI-CD
    steps:
         - uses: actions/checkout@v2
         - uses: ./
           with:
             credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
             project_id: "credible-skill-341215"
             action: save
             entity_kind: cloud-datastore-action-test
             entity_name: cloud-datastore-action-test-${{ matrix.action }}
             entity_data: file("./insert.json")

