name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Deploy para o BigQuery

        with:
          project_id: "credible-skill-341215"
          deliverables: ./table_schema.json
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          version: v1
      - name: Test
        run: ./sql_script.sql