name: "Deploy to BigQuery"
on:
  pull_request: {}
  push:
      branches: ["master"]

permissions: write-all

jobs:
  deploy_schemas:
    runs-on: ubuntu-latest
    name: Deploy to BigQuery
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Deploy schemas to BigQuery
        run: ./sql_script.sql
        env:
          gcp_project: 'credible-skill-341215'
          dataset_schema_directory: 'credible-skill-341215/dataset_name'
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
