name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    name: CI-CD
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Deploy to App Engine'
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          project_id: "credible-skill-341215"

          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          version: v1
      - name: Test
        run: ./sql_script.sql

