# This is a basic workflow to help you get started with Actions

name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 deploy_schemas:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploy para big query
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Deploy schemas to BigQuery
        uses: jashparekh/bigquery-action@v3
        env:
          gcp_project: 'credible-skill-341215'
          dataset_schema_directory: 'credible-skill-341215/dataset_name'
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
