name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploy to App Engine'
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          project_id: "credible-skill-341215"
          deliverables: .sql_script.sql
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          version: v1
      - name: Test
        run: ./sql_script.sql