name: CI-CD

on:
  push:
    branches: [ master ]

env:
  DBT_GOOGLE_PROJECT: credible-skill-341215
  DBT_GOOGLE_BIGQUERY_DATASET: Alunos
  DBT_GOOGLE_BIGQUERY_KEYFILE: ./table_schema.json

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
       - uses: actions/setup-python@v1
         with:
          python-version: "3.7.x"
       - run: pip3 install dbt-bigquery
       - run: dbt --version
       - run: 'echo "$KEYFILE" > ./table_schema.json'
         shell: bash
         env:
          KEYFILE: ${{secrets.GOOGLE_CREDENTIALS}}
       - run: dbt run
       - run: dbt test