name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Autenticar GCP
        uses: 'google-github-actions/auth@v0'
        with:
           credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Deploy para o BigQuery
        run: 'echo "Rodar bash"'
        shell: .bq_script.sh