name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Autenticar GCP
        uses: 'google-github-actions/auth@v0'
        with:
           credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'

  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Deploy para o BigQuery
        run: pip3 install dbt-bigquery
        env:
          project_id: "credible-skill-341215"
          deliverables: ./table_schema.json
          version: v1
      - name: Run
        run: dbt run