name: "Deploy para BigQuery"
on:
  pull_request: {}
  push:
      branches: ["master"]

jobs:
  deploy_schemas:
    runs-on: ubuntu-latest
    name: Deploy para BigQuery
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Deploy to App Engine'
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          project_id: "credible-skill-341215"
          deliverables: ./sql_script.sql
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          version: v1
      - name: Test
        run: ./sql_script.sql

