name: "Deploy para BigQuery"
on:
  pull_request: {}
  push:
      branches: ["master"]

jobs:
  deploy_schemas:
    runs-on: windows-latest
    name: Deploy para BigQuery
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'terraform@credible-skill-341215.iam.gserviceaccount.com'
      - name: Sql action
        uses: azure/sql-action@v1
        with:
          project: "credible-skill-341215"
          sql-file: ./sql_script.sql
        env:
          gcp_project: 'credible-skill-341215'
          dataset_schema_directory: 'credible-skill-341215/dataset_name'
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
