name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    name: CI-CD
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google Bigquery "Deploy table, view and other structure definitions" Action for Github Action
  # You may pin to the exact commit or the version.
  # uses: jashparekh/bigquery-action@0f6660576ba2a5246574edf336ab17fc011af9ec
        uses: jashparekh/bigquery-action@v3
        with:
    # Name of the GCP Project
         gcp_project: 'credible-skill-341215'
    # Path to the directory with schemas. Name of the directory should match with the dataset name in BigQuery
         dataset_schema_directory: ./sql_script.sql
    # Service account to autheticate with BigQuery
         credentials: ${{ secrets.GOOGLE_CREDENTIALS }}

