name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:


jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Autenticar GCP
        uses: 'google-github-actions/auth@v0'
        with:
           credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Deploy para o BigQuery
        run: bq query --nouse_legacy_sql \
          'INSERT INTO credible-skill-341215.Alunos.Tabela
          (ID,Nome,Telefone,Matricula,Status)
            values (1,"Maria",34267699,8888,"Inativo"), 
            (2,"Joaquim",34267677,7777,"Inativo"),
            (3,"Luis",34267666,6666,"Inativo"),
            (4,"Julia",34267655,5555,"Ativado"),
            (5,"Carla",34267644,4444,"Ativado")'