name: "Deploy para BigQuery"
on:
  pull_request: {}
  push:
      branches: ["master"]

jobs:
  deploy_schemas:
    runs-on: windows-latest
    name: Deploy to BigQuery
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Login
        uses: azure/login@v1
        with: 
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Sql action
        uses: azure/sql-action@v1
        with:
          project: "credible-skill-341215"
          sql-file: ./sql_script.sql
        env:
          gcp_project: 'credible-skill-341215'
          dataset_schema_directory: 'credible-skill-341215/dataset_name'
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
