name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Autenticar GCP
        uses: 'google-github-actions/auth@v0'
        with:
           credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'

  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Deploy para o BigQuery
        run: bq query --nouse_legacy_sql \
          'INSERT INTO `credible-skill-341215.Alunos.Tabela`(ID,Nome,Telefone,Matricula,Status)
            values (1,"Maria",34267699,8888,"Inativo")

          INSERT INTO `credible-skill-341215.Alunos.Tabela`(ID,Nome,Telefone,Matricula,Status)
          values (2,"Joaquim",34267677,7777,"Inativo")

          INSERT INTO `credible-skill-341215.Alunos.Tabela`(ID,Nome,Telefone,Matricula,Status)
          values (3,"Luis",34267666,6666,"Inativo")

          INSERT INTO `credible-skill-341215.Alunos.Tabela`(ID,Nome,Telefone,Matricula,Status)
          values (4,"Julia",34267655,5555,"Ativado")

          INSERT INTO `credible-skill-341215.Alunos.Tabela`(ID,Nome,Telefone,Matricula,Status)
          values (5,"Carla",34267644,4444,"Ativado")'
        env:
          project_id: "credible-skill-341215"
          deliverables: ./table_schema.json
          version: v1